### ISSUE TITLE
Test prod gift card

### ISSUE THREAD

**Issue by rndquu** [ubiquity/audit.ubq.fi#15]
Test prod gift card

**Comment by 0x4007** [comment]
How did the test go?

**Comment by rndquu** [comment]
> How did the test go?

I've setup production reloadly credentials for `pay.ubq.fi` and sandbox reloadly credentials for all of the cloudflare previews.

- sandbox (cloudflare preview URLs): card minting works fine.
- production (`pay.ubq.fi`): I haven't been able to mint because of https://github.com/ubiquity/pay.ubq.fi/issues/323

A little bit more context on https://github.com/ubiquity/pay.ubq.fi/issues/323: [this](https://github.com/ubiquity/audit.ubq.fi/issues/15#issuecomment-2421534945) buggy permit's owner is https://etherscan.io/address/0x9051eDa96dB419c967189F4Ac303a290F3327680 but the original signer is https://etherscan.io/address/0x51afbf762cdedc2683afecc2ccdd93da6a071ff8. Not sure how's that possible, working right now on the https://github.com/ubiquity-os-marketplace/text-conversation-rewards plugin.

**Comment by 0x4007** [comment]
> Not sure how's that possible

The only thing I can think of is a very long time ago, during a manual database migration, I misaligned a row or two, shifting everybody's wallet information. @whilefoo had the wrong wallet associated for like a year until they manually fixed it the other week. Not sure if thats related.

**Comment by rndquu** [comment]
> > Not sure how's that possible
> 
> The only thing I can think of is a very long time ago, during a manual database migration, I misaligned a row or two, shifting everybody's wallet information. @whilefoo had the wrong wallet associated for like a year until they manually fixed it the other week. Not sure if thats related.

Wallet misalignment in the DB could not cause the `owner != signer` permit signature mismatch

**Comment by whilefoo** [comment]
> A little bit more context on [ubiquity/pay.ubq.fi#323](https://github.com/ubiquity/pay.ubq.fi/issues/323): [this](https://github.com/ubiquity/audit.ubq.fi/issues/15#issuecomment-2421534945) buggy permit's owner is https://etherscan.io/address/0x9051eDa96dB419c967189F4Ac303a290F3327680 but the original signer is https://etherscan.io/address/0x51afbf762cdedc2683afecc2ccdd93da6a071ff8.

So this is only happening in production? Since you said it's working in sandbox I don't think this is an issue with the permit?

**Comment by rndquu** [comment]
> > A little bit more context on [ubiquity/pay.ubq.fi#323](https://github.com/ubiquity/pay.ubq.fi/issues/323): [this](https://github.com/ubiquity/audit.ubq.fi/issues/15#issuecomment-2421534945) buggy permit's owner is https://etherscan.io/address/0x9051eDa96dB419c967189F4Ac303a290F3327680 but the original signer is https://etherscan.io/address/0x51afbf762cdedc2683afecc2ccdd93da6a071ff8.
> 
> So this is only happening in production? Since you said it's working in sandbox I don't think this is an issue with the permit?

By "working in sandbox" I meant that virtual card minting works in `pay.ubq.fi` running with reloadly sandbox credentials and using permit [generated](https://github.com/ubiquity/pay.ubq.fi/blob/625a74be0adbb282cc46901ac2df945fcfc3fa6e/scripts/typescript/generate-erc20-permit-url.ts#L79) by `pay.ubq.fi` for testing purposes. TLDR; It turned out that there's a [bug](https://github.com/ubiquity-os/permit-generation/pull/91) in production in permit signature.
