### ISSUE TITLE
Audits: Owed Payments (Unpaid But Permitted)

### ISSUE THREAD

**Issue by 0x4007** [ubiquity/audit.ubq.fi#4]
A particularly useful feature now that we sort of have permits on hold: the ability to check if a permit was generated but the payout was not claimed yet.

---

Update Jan 2024:

We have a new column in the database that is meant to store the claim transaction link. 

Whenever the user claims using this UI, the UI should write the claim transaction link to the database. 

If the value in the database is null then it implies that the permit was not claimed.

**Comment by molecula451** [comment]
> A particularly useful feature now that we sort of have permits on hold: the ability to check if a permit was generated but the payout was not claimed yet.

Permits on hold? i guess we can close this or too outdated

**Comment by 0x4007** [comment]
It just means generated but not claimed. It's still relevant I think. Unless that was already implemented then yes we can close as unplanned. @FernandVEYRIER rfc

**Comment by gentlementlegen** [comment]
As of today, we should be seeing these permits as well. I they are not claimed, we should not have any link to the transaction but see the issue. However I don't think there would be any UI difference with the ones not claimed, or if there is no permit at all with the issue.

**Comment by 0x4007** [comment]
You can close as not planned @FernandVEYRIER if you think this is not necessary.
