### ISSUE TITLE
`audit` dApp: Show issues with unclaimed permits

### ISSUE THREAD

**Issue by rndquu** [ubiquity/audit.ubq.fi#5]
Depends on https://github.com/ubiquity/pay.ubq.fi/issues/100, https://github.com/ubiquity/pay.ubq.fi/issues/110

Right now the [audit page](https://pay.ubq.fi/audit) only displays issues with claimed permits.

We should also show issues with unclaimed permits.

**Comment by PhantomCracker** [comment]
Can we set the price so we can assign this?
Also, @rndquu we should show all the issues that are closed, right?

**Comment by rndquu** [comment]
> Also, @rndquu we should show all the issues that are closed, right?

Yes

**Comment by PhantomCracker** [comment]
Work in progress here, I think today I will finish it

**Comment by PhantomCracker** [comment]
@rndquu can I have the etherscan API and RPC url?

**Comment by rndquu** [comment]
> @rndquu can I have the etherscan API and RPC url?

Check the [code](https://github.com/ubiquity/pay.ubq.fi/blob/development/static/scripts/audit-report/constants.ts)

**Comment by PhantomCracker** [comment]
@rndquu  I am not sure what I do wrong here... 
<img width="628" alt="Screenshot 2023-08-03 at 18 52 47" src="https://github.com/ubiquity/pay.ubq.fi/assets/5438246/ec45973a-6b3c-4753-a217-2a1873506d1f">

**Comment by devpanther** [comment]
> @rndquu I am not sure what I do wrong here... 

You are supposed to be on the `/audit` path

**Comment by PhantomCracker** [comment]
> You are supposed to be on the `/audit` path

Can you be more specific please? Maybe you can provide an example of URL?... I just don't get it where this audit page is 😢
<img width="388" alt="Screenshot 2023-08-04 at 10 14 13" src="https://github.com/ubiquity/pay.ubq.fi/assets/5438246/d50fb9ff-4b98-4728-bb73-edeea00c1066">

**Comment by devpanther** [comment]
> > You are supposed to be on the `/audit` path
> 
> Can you be more specific please? Maybe you can provide an example of URL?... I just don't get it where this audit page is 😢
> <img width="388" alt="Screenshot 2023-08-04 at 10 14 13" src="https://github.com/ubiquity/pay.ubq.fi/assets/5438246/d50fb9ff-4b98-4728-bb73-edeea00c1066">
>  

Make it `http://localhost:8080/audit.html`

**Comment by PhantomCracker** [comment]
I guess that today I will release the PR :) I really hope so

**Comment by 0x4007** [comment]
You should be working on a draft pull request.

**Comment by PhantomCracker** [comment]
Ok, I will open it now.

**Comment by gentlementlegen** [comment]
This issue depends on https://github.com/ubiquity/pay.ubq.fi/issues/110, since it changes the logic to fetch the permits.

**Comment by rndquu** [comment]
> This issue depends on ubiquity/pay.ubq.fi#110, since it changes the logic to fetch the permits.

Thank you, updated the description

**Comment by gentlementlegen** [comment]
For unclaimed permits, I am currently displaying `UNCLAIMED` in the tx column, and I disabled the links for the tx and amount columns, to avoid having links redirecting to 404 pages. Please let me know if you desire a different behavior.

**Comment by 0x4007** [comment]
> For unclaimed permits, I am currently displaying `UNCLAIMED` in the tx column, and I disabled the links for the tx and amount columns, to avoid having links redirecting to 404 pages. Please let me know if you desire a different behavior.

It should be `null` in the database, and not say anything in the UI.

**Comment by gentlementlegen** [comment]
The request to the new repo is ready at https://github.com/ubiquity/audit.ubq.fi/pull/2

**Comment by 0x4007** [comment]
We need the labels restored before the payment can be made. 

@FernandVEYRIER how long did it take we can just use your time input

**Comment by gentlementlegen** [comment]
@pavlovcik Took < 2 hours, we spent more time reverting changes again and again as we discussed in the original PR here haha https://github.com/ubiquity/pay.ubq.fi/pull/172

**Comment by molecula451** [comment]
here is:

![image_2024-03-04_233533086](https://github.com/ubiquity/audit.ubq.fi/assets/41552663/cad67f97-502a-400c-8093-04793ca9597c)

**Comment by 0x4007** [comment]
Haha we did it at the same time. I'll just add a little cause of the real world feedback of how long it took and usually F is fast

**Comment by molecula451** [comment]
> Haha we did it at the same time. I'll just add a little cause of the real world feedback of how long it took and usually F is fast

indeed, haha re-do to < 4 hours

**Comment by 0x4007** [comment]
Looks like issue specification multiplier is not being applied. I think none of the multipliers work on the existing comment-incentives because also relevance isnt being applied to the final score. That's too bad. Looking forward to upgrading to the next version! 

https://github.com/ubiquity/ubiquibot-config/blob/development/.github/ubiquibot-config.yml#L15
